apiVersion: apps:v1
kind: Deployments
metadata: 
  name: backend
  namespace: backend-ns
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: backend
  template:
    metadata: 
      labels:
        app: backend
    spec: 
      containers:
      - name: httpd
        image: httpd:2.4
        ports: 
        - containerPort: 80
